const FALLBACK_SCHOLARSHIPS = [
  // ── National Schemes ──
  {
    title: 'NSP Central Sector Scheme of Scholarships for College and University Students',
    description: 'Merit-cum-means scholarship for students who have passed Class 12 with more than 80 percentile marks in the respective boards. Intended to meet day-to-day expenses while pursuing higher education.',
    courseRequired: ['Engineering', 'Medical', 'Arts', 'Commerce', 'Science', 'Law', 'Management'],
    categoryRequired: ['All'],
    incomeLimit: 450000,
    state: ['All'],
    minPercentage: 80,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: '₹10,000 – ₹20,000 per annum',
    source: 'National Scholarship Portal',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },
  {
    title: 'AICTE Pragati Scholarship for Girls',
    description: 'Scholarship for girl students pursuing technical education (Degree/Diploma). One scholarship per family per year.',
    courseRequired: ['Engineering'],
    categoryRequired: ['All'],
    incomeLimit: 800000,
    state: ['All'],
    minPercentage: 0,
    genderRequired: 'Female',
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    officialLink: 'https://www.aicte-india.org/bureaus/pgd/pragati-scholarship',
    amount: '₹30,000 per annum + ₹2,000 contingency',
    source: 'AICTE',
    sourceUrl: 'https://www.aicte-india.org',
    apiFetched: true,
  },
  {
    title: 'AICTE Saksham Scholarship for Specially-Abled Students',
    description: 'Scholarship for specially-abled students pursuing degree/diploma in technical courses through AICTE-approved institutions.',
    courseRequired: ['Engineering', 'Management'],
    categoryRequired: ['All'],
    incomeLimit: 800000,
    state: ['All'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    officialLink: 'https://www.aicte-india.org/bureaus/pgd/saksham',
    amount: '₹30,000 per annum + ₹2,000 contingency',
    source: 'AICTE',
    sourceUrl: 'https://www.aicte-india.org',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for SC Students',
    description: 'Government scholarship for students belonging to Scheduled Caste pursuing post-matriculation or post-secondary courses.',
    courseRequired: ['All'],
    categoryRequired: ['SC'],
    incomeLimit: 250000,
    state: ['All'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Maintenance allowance + tuition fee',
    source: 'Ministry of Social Justice and Empowerment',
    sourceUrl: 'https://socialjustice.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for ST Students',
    description: 'Scholarship for Scheduled Tribe students pursuing studies at post-matriculation or post-secondary stages.',
    courseRequired: ['All'],
    categoryRequired: ['ST'],
    incomeLimit: 250000,
    state: ['All'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Maintenance allowance + tuition fee',
    source: 'Ministry of Tribal Affairs',
    sourceUrl: 'https://tribal.nic.in',
    apiFetched: true,
  },
  {
    title: 'NSP Scholarship for Minorities (Pre-Matric)',
    description: 'Scholarship for students from minority communities (Muslim, Christian, Sikh, Buddhist, Zoroastrian, Jain) in Classes 1-10.',
    courseRequired: ['All'],
    categoryRequired: ['Minority'],
    incomeLimit: 100000,
    state: ['All'],
    minPercentage: 50,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: '₹1,000 – ₹10,000 per annum',
    source: 'Ministry of Minority Affairs',
    sourceUrl: 'https://minorityaffairs.gov.in',
    apiFetched: true,
  },
  {
    title: 'NSP Scholarship for Minorities (Post-Matric)',
    description: 'Post-matric scholarship for students from notified minority communities pursuing higher education.',
    courseRequired: ['All'],
    categoryRequired: ['Minority'],
    incomeLimit: 200000,
    state: ['All'],
    minPercentage: 50,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: '₹3,000 – ₹12,000 per annum',
    source: 'Ministry of Minority Affairs',
    sourceUrl: 'https://minorityaffairs.gov.in',
    apiFetched: true,
  },
  {
    title: 'UGC PG Scholarship for SC/ST Students',
    description: 'Post-graduate scholarship for students belonging to SC and ST categories pursuing regular full-time PG degree programmes.',
    courseRequired: ['Arts', 'Science', 'Commerce'],
    categoryRequired: ['SC', 'ST'],
    incomeLimit: 0,
    state: ['All'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
    officialLink: 'https://www.ugc.ac.in',
    amount: '₹3,100 per month',
    source: 'UGC',
    sourceUrl: 'https://www.ugc.ac.in',
    apiFetched: true,
  },
  {
    title: 'Ishan Uday Special Scholarship Scheme for NE Region',
    description: 'Scholarship for students domiciled in North Eastern states of India pursuing general degree courses.',
    courseRequired: ['Arts', 'Commerce', 'Science'],
    categoryRequired: ['All'],
    incomeLimit: 450000,
    state: ['Arunachal Pradesh', 'Assam', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Sikkim', 'Tripura'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    officialLink: 'https://www.ugc.ac.in',
    amount: '₹5,400 – ₹7,800 per month',
    source: 'UGC',
    sourceUrl: 'https://www.ugc.ac.in',
    apiFetched: true,
  },
  {
    title: 'DST INSPIRE Scholarship for Higher Education (SHE)',
    description: 'Scholarship for top 1% students in Class 12 board exams choosing to pursue natural and basic sciences at BSc and integrated MSc level.',
    courseRequired: ['Science'],
    categoryRequired: ['All'],
    incomeLimit: 0,
    state: ['All'],
    minPercentage: 85,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 100 * 24 * 60 * 60 * 1000),
    officialLink: 'https://www.online-inspire.gov.in',
    amount: '₹80,000 per annum + ₹20,000 mentorship',
    source: 'DST',
    sourceUrl: 'https://dst.gov.in',
    apiFetched: true,
  },
  {
    title: 'OBC Post Matric Scholarship',
    description: 'Post-matric scholarship for students belonging to Other Backward Classes pursuing studies at post-matriculation level.',
    courseRequired: ['All'],
    categoryRequired: ['OBC'],
    incomeLimit: 100000,
    state: ['All'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 80 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Maintenance allowance based on course',
    source: 'Ministry of Social Justice and Empowerment',
    sourceUrl: 'https://socialjustice.gov.in',
    apiFetched: true,
  },
  {
    title: 'Begum Hazrat Mahal National Scholarship for Minorities (Girls)',
    description: 'Scholarship for meritorious girl students belonging to minority communities who are studying in Class 9 to 12.',
    courseRequired: ['All'],
    categoryRequired: ['Minority'],
    incomeLimit: 200000,
    state: ['All'],
    minPercentage: 50,
    genderRequired: 'Female',
    deadline: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000),
    officialLink: 'https://www.maef.nic.in',
    amount: '₹5,000 – ₹6,000 per annum',
    source: 'Maulana Azad Education Foundation',
    sourceUrl: 'https://www.maef.nic.in',
    apiFetched: true,
  },

  // ── Karnataka ──
  {
    title: 'Post Matric Scholarship for SC Students — Karnataka',
    description: 'Post-matric scholarship for Scheduled Caste students domiciled in Karnataka pursuing engineering and technical courses in recognized institutions. Administered through the Karnataka SSP portal.',
    courseRequired: ['Engineering'],
    categoryRequired: ['SC'],
    incomeLimit: 200000,
    state: ['Karnataka'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 80 * 24 * 60 * 60 * 1000),
    officialLink: 'https://ssp.postmatric.karnataka.gov.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'Karnataka SSP',
    sourceUrl: 'https://ssp.postmatric.karnataka.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for Minority Students — Karnataka',
    description: 'Post-matric scholarship for students belonging to minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) domiciled in Karnataka pursuing medical and professional courses.',
    courseRequired: ['Medical'],
    categoryRequired: ['Minority'],
    incomeLimit: 200000,
    state: ['Karnataka'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Tuition fee + ₹550–₹1,200/month maintenance',
    source: 'NSP — Ministry of Minority Affairs',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for OBC Students — Karnataka',
    description: 'Post-matric scholarship for Other Backward Class students domiciled in Karnataka pursuing law and other professional courses in recognized universities and colleges.',
    courseRequired: ['Law'],
    categoryRequired: ['OBC'],
    incomeLimit: 100000,
    state: ['Karnataka'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 65 * 24 * 60 * 60 * 1000),
    officialLink: 'https://ssp.postmatric.karnataka.gov.in',
    amount: 'Maintenance allowance as per course',
    source: 'Karnataka SSP',
    sourceUrl: 'https://ssp.postmatric.karnataka.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for ST Students — Karnataka',
    description: 'Post-matric scholarship for Scheduled Tribe girl students from Karnataka pursuing science courses. Administered by the Karnataka Tribal Welfare Department through the SSP portal.',
    courseRequired: ['Science'],
    categoryRequired: ['ST'],
    incomeLimit: 200000,
    state: ['Karnataka'],
    minPercentage: 0,
    genderRequired: 'Female',
    deadline: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000),
    officialLink: 'https://ssp.postmatric.karnataka.gov.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'Karnataka SSP',
    sourceUrl: 'https://ssp.postmatric.karnataka.gov.in',
    apiFetched: true,
  },

  // ── Tamil Nadu ──
  {
    title: 'Post Matric Scholarship for SC/ST Students — Tamil Nadu',
    description: 'Post-matric scholarship for Scheduled Caste and Scheduled Tribe students domiciled in Tamil Nadu pursuing engineering programmes in AICTE-approved colleges. Full tuition fee reimbursement.',
    courseRequired: ['Engineering'],
    categoryRequired: ['SC', 'ST'],
    incomeLimit: 250000,
    state: ['Tamil Nadu'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Full tuition fee + maintenance allowance',
    source: 'NSP — Tamil Nadu Adi Dravidar Welfare',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for SC Students — Tamil Nadu (Law)',
    description: 'Post-matric scholarship for Scheduled Caste students domiciled in Tamil Nadu pursuing LLB and integrated law programmes in recognized law colleges and universities.',
    courseRequired: ['Law'],
    categoryRequired: ['SC'],
    incomeLimit: 250000,
    state: ['Tamil Nadu'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Tuition fee + ₹550–₹1,200/month maintenance',
    source: 'NSP — Tamil Nadu Adi Dravidar Welfare',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for Minority Students — Tamil Nadu',
    description: 'Post-matric scholarship for minority community students domiciled in Tamil Nadu pursuing arts, science and commerce courses in recognized colleges and universities.',
    courseRequired: ['Arts', 'Science', 'Commerce'],
    categoryRequired: ['Minority'],
    incomeLimit: 200000,
    state: ['Tamil Nadu'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: '₹380–₹1,000/month maintenance + tuition fee',
    source: 'NSP — Ministry of Minority Affairs',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for OBC Students — Tamil Nadu (Medical)',
    description: 'Post-matric scholarship for Other Backward Class girl students from Tamil Nadu pursuing MBBS, BDS and allied medical courses in government and aided medical colleges.',
    courseRequired: ['Medical'],
    categoryRequired: ['OBC'],
    incomeLimit: 100000,
    state: ['Tamil Nadu'],
    minPercentage: 0,
    genderRequired: 'Female',
    deadline: new Date(Date.now() + 85 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'NSP — Ministry of Social Justice',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },

  // ── Maharashtra ──
  {
    title: 'Post Matric Scholarship for OBC Students — Maharashtra (Engineering)',
    description: 'Post-matric scholarship for Other Backward Class students domiciled in Maharashtra pursuing engineering degrees in AICTE-approved colleges. Disbursed through the MahaDBT portal.',
    courseRequired: ['Engineering'],
    categoryRequired: ['OBC'],
    incomeLimit: 800000,
    state: ['Maharashtra'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000),
    officialLink: 'https://mahadbt.maharashtra.gov.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'MahaDBT — Government of Maharashtra',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for EWS Students — Maharashtra (Management)',
    description: 'Post-matric scholarship for Economically Weaker Section students from Maharashtra pursuing MBA and management courses in recognized institutions. Disbursed through MahaDBT.',
    courseRequired: ['Management'],
    categoryRequired: ['EWS'],
    incomeLimit: 800000,
    state: ['Maharashtra'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 65 * 24 * 60 * 60 * 1000),
    officialLink: 'https://mahadbt.maharashtra.gov.in',
    amount: 'Tuition fee reimbursement',
    source: 'MahaDBT — Government of Maharashtra',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for SC Students — Maharashtra (Medical)',
    description: 'Post-matric scholarship for Scheduled Caste girl students from Maharashtra pursuing MBBS, BDS and paramedical courses. Full tuition fee reimbursement through MahaDBT portal.',
    courseRequired: ['Medical'],
    categoryRequired: ['SC'],
    incomeLimit: 250000,
    state: ['Maharashtra'],
    minPercentage: 0,
    genderRequired: 'Female',
    deadline: new Date(Date.now() + 80 * 24 * 60 * 60 * 1000),
    officialLink: 'https://mahadbt.maharashtra.gov.in',
    amount: 'Full tuition fee + maintenance allowance',
    source: 'MahaDBT — Government of Maharashtra',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for Minority Students — Maharashtra (Polytechnic)',
    description: 'Post-matric scholarship for minority students from Maharashtra pursuing polytechnic diploma courses in government and aided polytechnic institutes. Disbursed through MahaDBT.',
    courseRequired: ['Polytechnic'],
    categoryRequired: ['Minority'],
    incomeLimit: 200000,
    state: ['Maharashtra'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000),
    officialLink: 'https://mahadbt.maharashtra.gov.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'MahaDBT — Government of Maharashtra',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    apiFetched: true,
  },

  // ── Uttar Pradesh ──
  {
    title: 'Post Matric Scholarship for SC Students — Uttar Pradesh (Engineering)',
    description: 'Post-matric scholarship for Scheduled Caste students domiciled in Uttar Pradesh pursuing engineering courses. Full tuition fee reimbursement through the UP Scholarship Portal.',
    courseRequired: ['Engineering'],
    categoryRequired: ['SC'],
    incomeLimit: 250000,
    state: ['Uttar Pradesh'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 85 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarship.up.gov.in',
    amount: 'Full tuition fee + maintenance allowance',
    source: 'UP Scholarship Portal',
    sourceUrl: 'https://scholarship.up.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for OBC Students — Uttar Pradesh (ITI)',
    description: 'Post-matric scholarship for Other Backward Class students from Uttar Pradesh pursuing ITI courses in government and private ITI institutes recognized by the NCVT.',
    courseRequired: ['ITI'],
    categoryRequired: ['OBC'],
    incomeLimit: 100000,
    state: ['Uttar Pradesh'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarship.up.gov.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'UP Scholarship Portal',
    sourceUrl: 'https://scholarship.up.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for Minority Students — Uttar Pradesh (Commerce)',
    description: 'Post-matric scholarship for minority community students domiciled in Uttar Pradesh pursuing BCom, MCom and other commerce courses in recognized colleges and universities.',
    courseRequired: ['Commerce'],
    categoryRequired: ['Minority'],
    incomeLimit: 200000,
    state: ['Uttar Pradesh'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarship.up.gov.in',
    amount: '₹380–₹1,000/month + tuition fee',
    source: 'UP Scholarship Portal',
    sourceUrl: 'https://scholarship.up.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for EWS Students — Uttar Pradesh (Medical)',
    description: 'Post-matric scholarship for Economically Weaker Section students from Uttar Pradesh pursuing MBBS, BDS and other medical courses in state medical colleges.',
    courseRequired: ['Medical'],
    categoryRequired: ['EWS'],
    incomeLimit: 800000,
    state: ['Uttar Pradesh'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarship.up.gov.in',
    amount: 'Full tuition fee',
    source: 'UP Scholarship Portal',
    sourceUrl: 'https://scholarship.up.gov.in',
    apiFetched: true,
  },

  // ── West Bengal ──
  {
    title: 'Swami Vivekananda Merit Cum Means Scholarship — West Bengal (Science)',
    description: 'Merit-cum-means scholarship for students from West Bengal pursuing BSc and MSc in natural and basic sciences. One of the highest-value state scholarships, disbursed by WB Higher Education Dept.',
    courseRequired: ['Science'],
    categoryRequired: ['All'],
    incomeLimit: 250000,
    state: ['West Bengal'],
    minPercentage: 75,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 95 * 24 * 60 * 60 * 1000),
    officialLink: 'https://svmcm.wbhed.gov.in',
    amount: '₹1,000–₹5,000 per month',
    source: 'West Bengal Higher Education Dept',
    sourceUrl: 'https://svmcm.wbhed.gov.in',
    apiFetched: true,
  },
  {
    title: 'Aikyashree Scholarship for Minority Students — West Bengal (Engineering)',
    description: 'Pre and post-matric scholarship for minority community students domiciled in West Bengal pursuing engineering courses. Administered by WB Minority Development Finance Corporation.',
    courseRequired: ['Engineering'],
    categoryRequired: ['Minority'],
    incomeLimit: 200000,
    state: ['West Bengal'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000),
    officialLink: 'https://wbmdfcscholarship.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'WB Minority Development Finance Corporation',
    sourceUrl: 'https://wbmdfcscholarship.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for SC Students — West Bengal (Arts)',
    description: 'Post-matric scholarship for Scheduled Caste students from West Bengal pursuing BA and MA in humanities and social sciences. Tuition fee reimbursement and maintenance allowance provided.',
    courseRequired: ['Arts'],
    categoryRequired: ['SC'],
    incomeLimit: 250000,
    state: ['West Bengal'],
    minPercentage: 0,
    genderRequired: 'All',
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Tuition fee + ₹550–₹1,200/month maintenance',
    source: 'NSP — West Bengal SC/ST Welfare',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },
  {
    title: 'Post Matric Scholarship for OBC Students — West Bengal (Polytechnic)',
    description: 'Post-matric scholarship for Other Backward Class girl students from West Bengal pursuing polytechnic diploma courses in government and aided polytechnic institutes.',
    courseRequired: ['Polytechnic'],
    categoryRequired: ['OBC'],
    incomeLimit: 150000,
    state: ['West Bengal'],
    minPercentage: 0,
    genderRequired: 'Female',
    deadline: new Date(Date.now() + 65 * 24 * 60 * 60 * 1000),
    officialLink: 'https://scholarships.gov.in',
    amount: 'Tuition fee + maintenance allowance',
    source: 'NSP — West Bengal OBC Welfare',
    sourceUrl: 'https://scholarships.gov.in',
    apiFetched: true,
  },
];

module.exports = FALLBACK_SCHOLARSHIPS;
